language: python

install: pip install -r requirements.txt

script:
- python manage.py makemigrations
- python manage.py migrate
- flake8 .
- black --diff .
- coverage run --source=polls,swe1app manage.py test

after_script:
- coveralls
